# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20160321_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='responsible_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='server.GroupMember'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='server.GroupMember'),
        ),
    ]
