# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
