# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20160321_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='server.GroupMember'),
        ),
    ]
