# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_remove_task_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
