# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20160414_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_completion_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
