# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20160421_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_completion_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
