# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
