# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_groupmember_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='userid',
        ),
    ]
